### PR TITLE
Revert "0.3.0 with Serialport upgrade"

### PR DESCRIPTION
**Pull request by soef**
Reverts soef/ioBroker.wm-bus#13

### CODE REVIEW

**Comment by Apollon77** [comment]
Is it not working?

**Comment by soef** [comment]
It was not working with a cul stick. I have fixed it in Version 3.0.1

**Comment by soef** [comment]
Version 0.3.1!

**Comment by Apollon77** [comment]
cool, sorry have overseen the used parser :-((

**Pull request closed without merging**
